### PR TITLE
Fix logical bug in decodeJson() function

### PR DESCRIPTION
**Pull request by crtlib**
😬

### CODE REVIEW

**Comment by bzikarsky** [comment]
While the description is not descriptive, this commit contains a rather important fix in regards to JSON unpacking. We ran into fun binary-soup-strings without this fix.

**Comment by kelunik** [comment]
Could you please add a test case?

**Comment by crtlib** [comment]
Added a simple test for `decodeJson()` function. Is it ok @kelunik ?

**Comment by kelunik** [comment]
I was thinking about an integration test reading a json value from the database.

**Comment by bzikarsky** [comment]
I am not sure whether MySQL/MariaDB can be coerced to sending base64 (or non-base64) JSON on purpose. WDYT @crtlib -you triaged this so far.

**Comment by crtlib** [comment]
@bzikarsky Hm, good question. Unfortunately, I can't find anything about it on the web 😒 
The test I've just pushed is failing for me on MySQL 8.0.22 (without the actual fix).
@kelunik Is it good enough to merge? Or maybe you can help with forcing base64 encoding, so I can enhance the test?

**Comment by bzikarsky** [comment]
Can you add a second testcase which runs this against the CI's integration test databases? Even if it's sometimes a NOOP, it's still valuable.

**Comment by R4c00n** [comment]
@bzikarsky Any hints on how to run it agains CI integration test database? Would really like to see this merged.

**Comment by kelunik** [comment]
Looking at the code, it's obviously wrong, so I've merged this now. Sorry for the long delay, will prepare a release soon.

**Comment by R4c00n** [comment]
@kelunik Nice, thanks!

**Comment by kelunik** [comment]
https://github.com/amphp/mysql/releases/tag/v2.1.2 has been tagged now! :rocket:

**Pull request merged**
