### PR TITLE
travis: add mariadb. change to container build

### PR DESCRIPTION
**Pull request by grooverdan**

### CODE REVIEW

**Comment by kelunik** [comment]
Do we really need 12 instead of 3 test runs? We want to test our library, not MariaDB. Any specific reason why you add MariaDB to all those MySQL libraries?

**Comment by grooverdan** [comment]
As you're writing the protocol from specification it can't hurt to see if mariadb and mysql implement them the same and in a compatible way to this client implementation. Happy to cut this down to test each latest mariadb version against only one php version. What do you think?

**Comment by kelunik** [comment]
I don't really care, I just saw that you opened similar PRs to a few other projects today. @bwoebi Should we just merge it? As they're mostly running in parallel, it doesn't really matter IMO.

**Comment by bwoebi** [comment]
That PR adds the addons, but it doesn't actually run the tests on a mariadb instance? Or am I missing anything?

**Comment by grooverdan** [comment]
There is still a travis bug (travis-ci/travis-ci/issues/4569) which doesn't enable the plugin in pull requests. It does work really- https://travis-ci.org/grooverdan/mysql :-)

**Comment by kelunik** [comment]
@bwoebi Could you please close or merge this PR? Thanks.

**Comment by grooverdan** [comment]
updated to resolve merge conflicts by rebasing on master. Used newer mariadb versions. mariadb-5.5 removed as package wouldn't override existing mysql-5.6 service on travis infrastructure. There are some test failures - different flags output. Perhaps this is allowable?

https://travis-ci.org/grooverdan/mysql/jobs/302234121

**Comment by grooverdan** [comment]
CI all green. even php nightlys (though they are allowed failures)

**Comment by trowski** [comment]
@grooverdan Any idea how to avoid this with a `READ COMMITTED` transaction? It only happens with mariadb 10.0. See the [mariadb branch](https://github.com/amphp/mysql/tree/mariadb).

**Comment by grooverdan** [comment]
you could "set session sql_log_bin=0" before the transaction if you aren't using the binary log for anything.

**Comment by trowski** [comment]
Manually merged via fe96ba7aeb0d282d5f1ff12fee1a150e05b286c5.

**Pull request closed without merging**
