### PR TITLE
Fix ignored port in getConnectionString()

### PR DESCRIPTION
**Pull request by bzikarsky**
Quick and obvious bugfix.

### CODE REVIEW

**Comment by bzikarsky** [comment]
It looks like the CI failed because the database sometimes failed to bootstrap. Unrelated to my change.

**Comment by staabm** [comment]
you should provide a unit test

**Comment by bzikarsky** [comment]
Possibly, but:
- The repo's unit-tests require a locally available `mysqld` binary without there being a `Dockerfile` or similar to run the tests in
- `ConnectionConfigTest` is not even tested at all in `v1.x`

If there is test-suite which can both run and changed easily I will gladly provide test cases. In this case, this is too much of a hustle.

**Comment by kelunik** [comment]
Maybe I'm missing something, but it seems pretty weird to parse the port from the host here at all if we always have a host and a port in the object.

**Comment by bzikarsky** [comment]
I think the main issue is the API design - having both a dedicated `$port` property and supporting `<host>:<port>` syntax on `$host`. That's redundant. Aynway: Ignoring `$port` in all varaints of `getConnectionString()` is just wrong. `$port` will be initalized to `3360` by default, so the code works the same, if the constructor argument is not used. In case it is, and there is no additional port hidden in `$host`, this patch will make sure, it is used.

**Comment by bzikarsky** [comment]
Is there something blocking this PR from my side?

**Comment by kelunik** [comment]
Nope.

**Comment by kelunik** [comment]
Thanks!

**Comment by bzikarsky** [comment]
Thanks for merging  - when can we expect a patch-release?

**Pull request merged**
